[package]
name = "wnr-pcap"
description = "WNR: raw network packet capturing and sniffing library (libpcap/Npcap port)."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = "0.2"
wnr-dnet = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
] }

[dev-dependencies]
